### ISSUE TITLE
why "filter only red color" ?

### ISSUE THREAD

**Issue by Bonsen** [lopuhin/kaggle-dsbowl-2018-dataset-fixes#1]
If we can just use grey mode mask?

**Comment by lopuhin** [comment]
This is a tool I used to create some masks: I made a copy of the original image, then I highlighted a missing nuclei with red color, and then extracted a binary mask from this image using this tool.

All resulting images don't have any red color, they are in the same format as in the original dataset. I hope that answers your question.

**Comment by Bonsen** [comment]
@lopuhin thanks!
