### ISSUE TITLE
Combine masks/fill in edges

### ISSUE THREAD

**Issue by brandenkmurray** [lopuhin/kaggle-dsbowl-2018-dataset-fixes#6]
There are some masks which are only 1 pixel wide along on the edges, but should probably either combined with another mask or deleted and the edge of the other mask filled in.

Image: `8d29c5a03e0560c8f9338e8eb7bccf47930149c8173f9ba4b9279fb87d86cf6d`
Issue: I believe `777459648d2c4c18fe8df79e284fbec4decc5f3ffaf26930ec7d3d457b84ae62` should be combined with `ad8de64200516edc0cf217f12b5cd87702fe9d54ba8e15c8ea0ebad72491458e`

![8d29c5a03e0560c8f9338e8eb7bccf47930149c8173f9ba4b9279fb87d86cf6d](https://user-images.githubusercontent.com/8684326/36919915-d9ba0bb8-1e13-11e8-860b-4656f584289f.png)
![777459648d2c4c18fe8df79e284fbec4decc5f3ffaf26930ec7d3d457b84ae62](https://user-images.githubusercontent.com/8684326/36919939-eca547ec-1e13-11e8-8e6a-ae81e95452a6.png)
![ad8de64200516edc0cf217f12b5cd87702fe9d54ba8e15c8ea0ebad72491458e](https://user-images.githubusercontent.com/8684326/36919940-ecbcbddc-1e13-11e8-9b60-58203303ad8e.png)

Image: `a1777737270c5f96c4523dff76e4097756f8f7d4c9d59bac079e31f9510deabd`
Issue: `069acba0cce8b22a267edd80e6c4303d9f8dd980bdcea0cf2569079b02cf6b41` should be combined with `88d98f2f5dc40a50963a3acea6c2bf8b42e4dc54f3bb8e13efd182f2342b9b9c`
`88d98f2f5dc40a50963a3acea6c2bf8b42e4dc54f3bb8e13efd182f2342b9b9c` should also be separated into two masks??

![a1777737270c5f96c4523dff76e4097756f8f7d4c9d59bac079e31f9510deabd](https://user-images.githubusercontent.com/8684326/36920070-65a16b1c-1e14-11e8-9802-0edd09a33bca.png)
![88d98f2f5dc40a50963a3acea6c2bf8b42e4dc54f3bb8e13efd182f2342b9b9c](https://user-images.githubusercontent.com/8684326/36920080-752e2070-1e14-11e8-9e31-f6ec8c977ea3.png)
![069acba0cce8b22a267edd80e6c4303d9f8dd980bdcea0cf2569079b02cf6b41](https://user-images.githubusercontent.com/8684326/36920081-7545344a-1e14-11e8-8f53-d5a9347b7f57.png)

Image: `a5fe0b7412dd152c41f7afc34ffdf276d4261b6942fa6d36803648e90f2cfc06`
Issue: `2ec5a0547b47b663b91224a0b0b031ba26c6d81dd8c2271a0142ff50e7a3c90e` should be combined with `addcb7a8c8e685bea3fd027d4df752d91bc4425ef42cd5c280f02a635598b71f`

![a5fe0b7412dd152c41f7afc34ffdf276d4261b6942fa6d36803648e90f2cfc06](https://user-images.githubusercontent.com/8684326/36920195-c441ba14-1e14-11e8-9948-cfba1a302e3b.png)
![2ec5a0547b47b663b91224a0b0b031ba26c6d81dd8c2271a0142ff50e7a3c90e](https://user-images.githubusercontent.com/8684326/36920215-d0bee33e-1e14-11e8-871f-076ccedbc0c2.png)
![addcb7a8c8e685bea3fd027d4df752d91bc4425ef42cd5c280f02a635598b71f](https://user-images.githubusercontent.com/8684326/36920217-d0d6866a-1e14-11e8-927f-ca976543a8d5.png)

Image: `ac782d2cad7f515ce7276926209820e386248e3d619b2df81e22d5e3c160b7cb`
Issue: `e707c768392b287baffc9307f2dc0d6a9993e40bcae8945caf0925bc789e4259` should be combined with `fe6f816584d1ef48bab8b53ab506da6a0453dfc5b3a54c378fa8276902ed98df` or `fe6f816584d1ef48bab8b53ab506da6a0453dfc5b3a54c378fa8276902ed98df` should have its edge filled in.

![ac782d2cad7f515ce7276926209820e386248e3d619b2df81e22d5e3c160b7cb](https://user-images.githubusercontent.com/8684326/36920251-fbe31490-1e14-11e8-98db-2e3e5cf885fb.png)
![fe6f816584d1ef48bab8b53ab506da6a0453dfc5b3a54c378fa8276902ed98df](https://user-images.githubusercontent.com/8684326/36920268-0b71aee4-1e15-11e8-8475-ef43f09ed55b.png)
![e707c768392b287baffc9307f2dc0d6a9993e40bcae8945caf0925bc789e4259](https://user-images.githubusercontent.com/8684326/36920269-0b8db030-1e15-11e8-9abb-4e9ce4b52974.png)

Image: `b4de1e3eec159d8af1bd5447696f8996c31709edaf33e26ba9613816705847db`
Issue: `b9a160bc22b20d83a529f71b75f8ac11bed4f306c3d02d3d5496cefcda91666a` should be combined with `f96baae7af98e61f05e147ca0f83180495d9e19123653817c618ded7c4d18fd4`
![b4de1e3eec159d8af1bd5447696f8996c31709edaf33e26ba9613816705847db](https://user-images.githubusercontent.com/8684326/36920311-332e3772-1e15-11e8-90a0-1c7e960a2539.png)
![f96baae7af98e61f05e147ca0f83180495d9e19123653817c618ded7c4d18fd4](https://user-images.githubusercontent.com/8684326/36920329-3d73c6c0-1e15-11e8-888a-f510650e1491.png)
![b9a160bc22b20d83a529f71b75f8ac11bed4f306c3d02d3d5496cefcda91666a](https://user-images.githubusercontent.com/8684326/36920331-3d8c9682-1e15-11e8-854e-56ce89c06da4.png)

Image: `d4d88391bc399a3715440d4da9f8b7a973e010dc1edd9551df2e5a538685add5`
Issue: `1f06b1d1ef191b4a0ecf28636d017d143114ac3e4760f0eb35f56af006d41a62` should be combined with `ba6ebce2a5f948a6e5a25a9704911137e50431948300d7fc55809229e85420f0` or `ba6ebce2a5f948a6e5a25a9704911137e50431948300d7fc55809229e85420f0` should have its edge filled in.
![d4d88391bc399a3715440d4da9f8b7a973e010dc1edd9551df2e5a538685add5](https://user-images.githubusercontent.com/8684326/36920362-5c487398-1e15-11e8-9074-f99cbf60d10c.png)
![1f06b1d1ef191b4a0ecf28636d017d143114ac3e4760f0eb35f56af006d41a62](https://user-images.githubusercontent.com/8684326/36920376-64da1a2a-1e15-11e8-9b5c-5efbc0b155c5.png)
![ba6ebce2a5f948a6e5a25a9704911137e50431948300d7fc55809229e85420f0](https://user-images.githubusercontent.com/8684326/36920377-64f2b1c0-1e15-11e8-80c1-a953635fd972.png)

Image: `e49fc2b4f1f39d481a6525225ab3f688be5c87f56884456ad54c953315efae83`
Issue: `e969172b62b37ba15754478b69cefce1bf61534b46b4ac9e80e07a410815cfdc` should be combined with `20088856907c46ef9c9208ebabc5c75da1f177138ddd705697929ad00a97e9b9`
![e49fc2b4f1f39d481a6525225ab3f688be5c87f56884456ad54c953315efae83](https://user-images.githubusercontent.com/8684326/36920412-7aa6cbaa-1e15-11e8-90e7-10d9c1d7b9a4.png)
![e969172b62b37ba15754478b69cefce1bf61534b46b4ac9e80e07a410815cfdc](https://user-images.githubusercontent.com/8684326/36920435-84f9da3e-1e15-11e8-8d47-9b730d12914e.png)
![20088856907c46ef9c9208ebabc5c75da1f177138ddd705697929ad00a97e9b9](https://user-images.githubusercontent.com/8684326/36920436-854ff630-1e15-11e8-98ce-22c1c3d4fddf.png)

**Comment by lopuhin** [comment]
Thanks, I agree with everything except for images b4de1e3eec159d8af1bd5447696f8996c31709edaf33e26ba9613816705847db and d4d88391bc399a3715440d4da9f8b7a973e010dc1edd9551df2e5a538685add5 - the masks for them seem to not quite match?

**Comment by brandenkmurray** [comment]
They don't match but I think in those cases the edges need to be filled in and the 1px wide mask deleted. Also, the masks for `ac782d2cad7f515ce7276926209820e386248e3d619b2df81e22d5e3c160b7cb` overlap so I've deleted the incorrect one.

**Comment by lopuhin** [comment]
I think all issues are fixed in #7, feel free to reopen if anything is missing.
